package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Thursday, 11 May, 2023 1:49:50 PM IST
*/

public interface CalculatorOperations 
{
  float add (float x, float y);
  float subtract (float x, float y);
  float multiply (float x, float y);
  float divide (float x, float y);
} // interface CalculatorOperations
